export const buttonValues = [
  { id: 1, name: 'C' },
  { id: 2, name: '7' },
  { id: 20, name: '8' },
  { id: 3, name: '9' },
  { id: 4, name: '*' },
  { id: 5, name: '-' },
  { id: 6, name: '4' },
  { id: 7, name: '5' },
  { id: 8, name: '6' },
  { id: 9, name: '/' },
  { id: 10, name: '+' },
  { id: 11, name: '1' },
  { id: 12, name: '2' },
  { id: 13, name: '3' },
  { id: 14, name: '=' },
  { id: 15, name: '.' },
  { id: 16, name: '(' },
  { id: 17, name: '0' },
  { id: 18, name: ')' },
  { id: 19, name: 'CE' },
];
